name: tlp_ui
description: A desktop app to configure TLP
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.0.0
  equatable: ^2.0.5
  file_picker: ^10.0.0
  flutter_bloc: ^9.0.0
  flutter_essentials_kit: ^2.4.0
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^3.0.0
  hydrated_bloc: ^10.0.0
  intl: any
  path: ^1.8.3
  path_provider: ^2.1.1
  pine: ^1.0.2
  provider: ^6.0.5
  reactive_forms: ^18.0.0
  talker: ^4.0.0
  yaru: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator:
  bloc_test: ^10.0.0
  build_runner: ^2.4.6
  data_fixture_dart: ^3.0.0
  flutter_lints: ^3.0.0
  freezed:
  mockito: ^5.4.2
  mocktail: ^1.0.1

flutter:
  generate: true
  uses-material-design: true
