name: tlp_ui
description: A desktop app to configure TLP
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  yaru: ^1.1.0
  pine: ^1.0.2
  auto_route: ^10.0.0
  flutter_bloc: ^9.0.0
  freezed_annotation: ^3.0.0
  hydrated_bloc: ^9.1.2
  intl: any
  path_provider: ^2.1.1
  provider: ^6.0.5
  flutter_essentials_kit: ^2.4.0
  font_awesome_flutter: ^10.6.0
  equatable: ^2.0.5
  talker: ^3.1.4
  reactive_forms: ^16.1.1
  yaru_widgets: ^3.2.2
  file_picker: ^10.0.0
  flutter_staggered_grid_view: ^0.7.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.5
  auto_route_generator:
  build_runner: ^2.4.6
  freezed:
  mockito: ^5.4.2
  mocktail: ^1.0.1
  data_fixture_dart: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
